apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4ba
spec:
  encryptedData:
    .dockerconfigjson: AgAUsXS7CW1ogdxJiZYPXhcwpvNldOblr+4/fIYlpoWwcN6lDn3G7a8SVFSeLVdgy0J7IiAQg3QhQoIu9UMwk29kE1HqBSdV4xf+pL0VJZYwuv6xK4CXDECIeKt/gVfliq4zSb8pXEgQWIHV6RvvU+27JlDSXxYj29/u0R+6H2gV20B2xoMqwXwvrmU4RdvYgSXT1baX1MxIGX1b916eMhiEwiQbxbxBYioS+XfloSk4F08tfGiHUtbepyYSKlqFfpwdwbAC68bgE1zFbqfmmQiZIf8jT4pUNT3Yka9m5MubLxJpF9e/ceqaDP8vIZ4TZGwsVcwEkKjaxTbRtRGOJ1Mr2MT4wRJvFCEJvWVFFGBDRovstiXPz37kxfI8WbnEyI3Qlfl5QgFD40Q0uHsMJszq8MV6INDxCgYyDp23m9fKmT9OSKZoVB4m/KhLLVhKBJRUC8R1Y0mrXU82Gq7CizBuN3LDsh1WN321LVg/dEITxgRv9trNk+djwPwRaRKr5ZJ9vAST2pC1rv1ctAJ+0oydBdNcJ7cx8Z7+mo92hu80bBPEnAqwBGDB3D1fXbAuBvtWp6z7gr76A72loJYalSU1DroEcsLHouc8dUGUR7EBiTr8SQGTjO5A1gOuXTdGLwIXLY6U6MeVrlh2n0SDs+lASaNLzJWwhDCOSHXb996bKtcXlyEZfswrbRzpzrf3u8lnzJZHvSqdv4bEAeUaPstUATdIP7ojccegl5QW2Mz63wMXTw62tvmfD9LZ/B1lDB7ta2C2eDMuhnb35e8zOnjk8XKxOiPW5reQvq5erXKBWyMkLprcJTxNXHP0XMQBO3Gxa2kUotTYuW3ocE2HBdxKkPxHChog+4IJzv+1FIBl1aOffvKnCzGRe3NteHMOo2MOLnlYWs+/giyGUd0GRNV/EvxTqbKctI/5xj4yhvQlvsuiyX+B68Ug28izD8rKgxHQ5dC9ByBN75MWtxR3VXmjO+r99D7NySVfGdVL1/zRdBjfZlPWBt5pEEF/nXgWail8h2V0ZzFIHfPXTkkbGWir8NuzyxoLN5McLto0BJjK5cI89dLEQ2f5KB066KN7rPi7eNUJqIMWJvy4aytGZzMjd1wRZk0gW4rmRkWxTr18ssHhdf7s3ePnGYcTyE2z6n11LKgq11D0/H8qMMQ6GSSPiKybXwwyT2W7ekzql3iPzNUy6zGjubzYlt9NGIjY+yHDUPkCJHIupyeCDiGVWXwRwmK6UxMG0DIH/eIJUKYD5Kl1q/JqhY1I6gxrv3uLF93QuSDy0Sv5+FbR6/Z8jwCnwEDOqgZjvMcK5j1dtKrYG0t4gi/7YqVR4xg1DGrBH5mCSGPZVzXgxnurB67dIX7aXFgZdz7qea5p0lDWzwqJ0E2QSmFa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4ba
    type: kubernetes.io/dockerconfigjson

