"cp4ba":
  "db_server": "161.202.168.37"
  "namespace": "cp4ba"
  "odm_db_name": "odmdb"
  "odm_db_port": "50000"
  "odm_db_type": "db2"
  "odm_image_repository": "cp.icr.io/cp/cp4a/odm"
  "odm_image_tag": "21.0.3-IF009"
  "odm_image_version": "21.0.3"
  "storageclass_block": "ibmc-vpc-block-10iops-tier"
  "storageclass_fast": "portworx-db2-rwx-sc"
  "storageclass_medium": "portworx-db2-rwx-sc"
  "storageclass_slow": "portworx-db2-rwx-sc"
"odmdbsecret":
  "db_password": "P@ssw0rd"
  "db_user": "db2inst1"
  "namespace": "cp4ba"
"odmldapsecret":
  "ldapPassword": "UEBzc3cwcmQ="
  "ldapUsername": "Y3BhZG1pbg=="
  "namespace": "cp4ba"
"values_file": "values-default.yaml"

